openapi: 3.1.0
info:
  title: FastAPI
  version: 0.8.0
servers:
  - url: https://dva.test.mgo.irealisatie.nl
    description: MGO TEST proxy
  - url: https://dva.acc.mgo.irealisatie.nl
    description: MGO Acceptance proxy
paths:
  "oidc/start":
    post:
      tags:
      - OIDC
      summary: idc Start
      operationId: oidc_start_oidc_start_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StartRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
#                $ref: "#/components/schemas/SearchResponse"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    StartRequest:
      properties:
        client_callback_url:
          type: string
          title: Client Callback Url
      type: object
      required:
        - client_callback_url
      title: StartRequest
#    SearchResponse:
#      properties:
#        organizations:
#          items:
#            $ref: "#/components/schemas/Organization"
#          type: array
#          title: Organizations
#      type: object
#      required:
#      - organizations
#      title: SearchResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
