/*
 *  Copyright (c) 2024 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
 *  Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2
 *
 *  SPDX-License-Identifier: EUPL-1.2
 */

import AuthorizationMiddleware
import OpenAPIRuntime
import OpenAPIURLSession
import Foundation

public class RemoteAuthenticationClient {
	
	/// Autogenerated api client with OpenAPI-generator
	private var client: Client
	
	/// Create a Remote Authentication Client

	/// - Parameter serverUrl: the url for the service
	/// - Parameter username: authentication user name
	/// - Parameter password: authentication password
	required public init(serverUrl: Foundation.URL, username: String?, password: String?) {
		
		if let username, let password {
			let authenticationMiddleWare = AuthorizationMiddleware(
				username: username,
				password: password
			)
			self.client = Client(
				serverURL: serverUrl,
				transport: URLSessionTransport(),
				middlewares: [authenticationMiddleWare]
			)
		} else {
			self.client = Client(
				serverURL: serverUrl,
				transport: URLSessionTransport()
			)
		}
	}
	
	/// Get the authentication url
	/// - Parameter callbackUrl: the callback url to redirect to
	public func getAuthenticationUrl(callbackUrl: String) async throws {
		
		let request = Components.Schemas.StartRequest(client_callback_url: callbackUrl)
		let input = Operations.oidc_start_oidc_start_post.Input(body: .json(request))
		let response = try await client.oidc_start_oidc_start_post(input)
		
		let xxxx = try response.ok.body
		
		print("getAuthenticationUrl: \(xxxx)")
	}
}
