version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Amsterdam

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Amsterdam

# Swift Packages
  - package-ecosystem: "swift"
    directory: "/Packages/FHIRClient"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/FHIRExtensions"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/LocalisationService"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/Managers"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/MGOFoundation"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/MGOTest"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/MGOUI"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/RestrictedBrowser"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/ReusableUI"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/RijksoverheidFont"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/Theme"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam
