version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Amsterdam

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Europe/Amsterdam

# Swift Packages
  - package-ecosystem: "swift"
    directory: "/Packages/AuthorizationMiddleware"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/CopyImport"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/FeatureFlag"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/FHIRClient"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/FileStorage"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/GitHubArtifactDownload"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam
      
  - package-ecosystem: "swift"
    directory: "/Packages/HCIMCore"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam
      
# No dependency check for JailBreakDetector due to licensing issue

  - package-ecosystem: "swift"
    directory: "/Packages/LocalAuthenticationProvider"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/LocalisationService"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/MGOCommandLine"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/MGODebug"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/MGOFoundation"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/MGORepository"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/MGOTest"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/MGOUI"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/Observatory"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/PatientFriendlyTerms"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/PdfExport"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/RemoteAuthentication"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/RemoteConfiguration"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/RestrictedBrowser"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/ReusableUI"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/RijksoverheidFont"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/Sanitizer"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/SecureUserSettings"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

  - package-ecosystem: "swift"
    directory: "/Packages/Theme"
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: Europe/Amsterdam

