# Project info
sonar.organization=vws
sonar.projectKey=nl-mgo-app-ios-private
sonar.projectName=nl-mgo-app-ios-private

# Info links shown in SonarCloud
sonar.links.homepage=https://github.com/minvws/nl-mgo-app-ios-private

# Encoding and language specific properties
sonar.sourceEncoding=UTF-8

# Analysis scoping
sonar.sources=Sources, Packages
sonar.tests=MGOTests
sonar.exclusions=MGOTests, MGOUITests, Packages/**/Package.swift, Packages/**/Tests/*, Packages/**/Tests/**/*, Packages/**/Tests/**/**/*, Packages/**/Tests/**/**/**/*, Packages/CopyImport/Sources/CopyImport.swift
# Don't analyze testfiles in Packages

# Code coverage
sonar.coverageReportPaths=coverage.xml
sonar.coverage.exclusions=Sources/MGO/Core/AppDelegate.swift, Sources/MGO/Core/LaunchArgumentsHandler.swift,  Sources/MGO/Core/MGOApp.swift, Packages/ParsingCore/Sources/UISchema/UISchema.swift
