/*
 *  Copyright (c) 2024 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
 *  Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2
 *
 *  SPDX-License-Identifier: EUPL-1.2
 */

import OpenAPIRuntime
import OpenAPIURLSession

public typealias HealthcareProvider = Components.Schemas.Organization

public protocol LocalisationServiceClientProtocol {
	
	/// Initializer
	init?()
	
	/// Search for all the healthcare providers with this city and name
	/// - Parameters:
	///   - city: the city to search with
	///   - name: the name to search with
	/// - Returns: An (empty) array of Healthcare Providers
	func searchHealthcareProviders(city: String, name: String) async throws -> [HealthcareProvider]
}

public class LocalisationServiceClient: LocalisationServiceClientProtocol {
	
	/// Autogenerated api client with OpenAPI-generator
	private var client: Client
	
	/// Initializer
	required public init?() {
		
		guard let serverUrl = try? Servers.server1() else { return nil }
		self.client = Client(serverURL: serverUrl, transport: URLSessionTransport())
	}
	
	/// Search for all the healthcare providers with this city and name
	/// - Parameters:
	///   - city: the city to search with
	///   - name: the name to search with
	/// - Returns: An (empty) array of Healthcare Providers
	public func searchHealthcareProviders(city: String, name: String) async throws -> [HealthcareProvider] {
		
		let searchRequest = Components.Schemas.SearchRequest(name: name, city: city)
		let input = Operations.read_item_localization_organization_search_post.Input(body: .json(searchRequest))
		let response = try await client.read_item_localization_organization_search_post(input)
		let organizations = try response.ok.body.json.organizations
		return organizations
	}
}
