/*
 *  SPDX-FileCopyrightText: 2025 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
 *  SPDX-License-Identifier: EUPL-1.2
 */

import OpenAPIRuntime
import OpenAPIURLSession
import Foundation

public protocol RemoteConfigurationClientProtocol {
	
	/// Create a Remote Configuration Client
	/// - Parameter serverUrl: the url for the service
	init(serverUrl: Foundation.URL)
	
	/// Fetch the remote configuration
	/// - Returns: the remote configuration
	func fetchRemoteConfig() async throws -> RemoteConfig
}

public class RemoteConfigurationClient: RemoteConfigurationClientProtocol {
	
	/// Autogenerated api client with OpenAPI-generator
	private var client: Client
	
	/// Create a Remote Configuration Client
	/// - Parameter serverUrl: the url for the service
	required public init(serverUrl: Foundation.URL) {
		
		self.client = Client(serverURL: serverUrl, transport: URLSessionTransport())
	}
	
	/// Fetch the remote configuration
	/// - Returns: the remote configuration
	public func fetchRemoteConfig() async throws -> RemoteConfig {
		
		let response = try await client.get_sol_config()
		let config = try response.ok.body.json
		return config
	}
}
