/*
 *  SPDX-FileCopyrightText: 2026 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
 *  SPDX-License-Identifier: EUPL-1.2
 */

import AuthorizationMiddleware
import OpenAPIRuntime
import OpenAPIURLSession
import Foundation

public protocol RemoteConfigurationClientProtocol: Sendable {
	
	/// Create a Remote Configuration Client
	/// - Parameter serverUrl: the url for the service
	init(serverUrl: Foundation.URL)
	
	/// Create a Remote Configuration Client
	/// - Parameter serverUrl: the url for the service
	/// - Parameter username: authentication user name
	/// - Parameter password: authentication password
	init(serverUrl: Foundation.URL, username: String, password: String)
	
	/// Fetch the remote configuration
	/// - Returns: the remote configuration
	func fetchRemoteConfig() async throws -> RemoteConfig
}

public final class RemoteConfigurationClient: RemoteConfigurationClientProtocol {
	
	/// Autogenerated api client with OpenAPI-generator
	private let client: Client
	
	/// Create a Remote Configuration Client
	/// - Parameter serverUrl: the url for the service
	required public init(serverUrl: Foundation.URL) {
		
		self.client = Client(
			serverURL: serverUrl,
			transport: URLSessionTransport()
		)
	}
	
	/// Create a Remote Configuration Client
	/// - Parameter serverUrl: the url for the service
	/// - Parameter username: authentication user name
	/// - Parameter password: authentication password
	required public init(serverUrl: Foundation.URL, username: String, password: String) {
		
		let authenticationMiddleWare = AuthorizationMiddleware(
			username: username,
			password: password
		)
		self.client = Client(
			serverURL: serverUrl,
			transport: URLSessionTransport(),
			middlewares: [authenticationMiddleWare]
		)
	}
	
	/// Fetch the remote configuration
	/// - Returns: the remote configuration
	public func fetchRemoteConfig() async throws -> RemoteConfig {
		
		let response = try await client.get_sol_config()
		let config = try response.ok.body.json
		return config
	}
}
