/*
 *  Copyright (c) 2024 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
 *  Licensed under the EUROPEAN UNION PUBLIC LICENCE v. 1.2
 *
 *  SPDX-License-Identifier: EUPL-1.2
 */

import OpenAPIRuntime
import OpenAPIURLSession

public protocol RemoteConfigurationClientProtocol {
	
	/// Initializer
	init?()
	
	/// Fetch the remote configuration
	/// - Returns: the remote configuration
	func fetchRemoteConfig() async throws -> RemoteConfig
}

public class RemoteConfigurationClient: RemoteConfigurationClientProtocol {
	
	/// Autogenerated api client with OpenAPI-generator
	private var client: Client
	
	/// Initializer
	required public init?() {
		
		guard let serverUrl = try? Servers.server1() else { return nil }
		self.client = Client(serverURL: serverUrl, transport: URLSessionTransport())
	}
	
	/// Fetch the remote configuration
	/// - Returns: the remote configuration
	public func fetchRemoteConfig() async throws -> RemoteConfig {
		
		let response = try await client.get_sol_v1_sol_mgo_sol_config()
		let config = try response.ok.body.json
		return config
	}
}
