openapi: 3.1.0
info:
  title: RemoteConfig
  description: The remote config with settings and feature flags.
  version: 0.1.0
servers:
  - url: https://app-api.test.mgo.irealisatie.nl/v1/mgo
    description: Application API TEST
  - url: https://app-api.acc.mgo.irealisatie.nl/v1/mgo
    description: Application API Acceptance
paths:
  "config":
    get:
      summary: Get the remote configuration
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RemoteConfig"
components:
  schemas:
    RemoteConfig:
      properties:
        iosMinimumVersion:
          type: string
          title: minimumVersion
#        iosRecommendedVersion:
#          type: string
#          title: recommendedVersion
#        appDeactivated:
#          type: boolean
#          title: appDeactivated
      required:
        - iosMinimumVersion
#        - iosRecommendedVersion
#        - appDeactivated

