/*
 *  SPDX-FileCopyrightText: 2026 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
 *  SPDX-License-Identifier: EUPL-1.2
 */

import OpenAPICore
import OpenAPIMiddleware
import Foundation
import MGODebug

/// The API Client for the Localization dataset endpoints.
public final class LocalizationAPIClient: LocalizationAPIClientProtocol {
	
	/// The url of the server
	private let serverURL: URL
	
	/// Optional authorization middleware for basic auth
	private let authorizationMiddleware: AuthorizationMiddleware?
	
	/// Create an Organization Dataset API Client with Basic Auth.
	/// - Parameters:
	///   - url: the url to the server
	///   - username: authentication user name
	///   - password: authentication password
	required public init(
		_ url: Foundation.URL,
		username: String,
		password: String
	) {
		
		self.serverURL = url
		self.authorizationMiddleware = AuthorizationMiddleware(
			username: username,
			password: password
		)
	}
	
	/// Create an Organization Dataset API Client without authentication.
	/// - Parameter url: the url to the server
	required public init(_ url: Foundation.URL) {
		
		self.serverURL = url
		self.authorizationMiddleware = nil
	}
	
	/// Builds the autogenerated OpenAPI client with the configured middleware stack.
	private func setUpClient() -> Client {
		
		var middlewares = [any ClientMiddleware]()
		if let authorizationMiddleware {
			middlewares.append(authorizationMiddleware)
		}
		middlewares.append(
			StripHeaderEncodingMiddleware(strippableHeaders: [.ifNoneMatch])
		)
		return Client(
			serverURL: serverURL,
			transport: URLSessionTransport(),
			middlewares: middlewares
		)
	}
	
	/// Fetch the given dataset from the remote server.
	/// - Parameters:
	///   - kind: which dataset to fetch
	///   - eTag: The ETag for conditional request
	/// - Returns: tuple of status code, eTag and raw data (nil on 304)
	public func fetch(
		_ kind: LocalizationEndpoint,
		eTag: String?
	) async throws -> (statusCode: Int, eTag: String?, data: Data?) {
		
		let client = setUpClient()
		switch kind {
			case .organizations:
				return try await fetchOrganizations(client: client, eTag: eTag)
			case .endpoints:
				return try await fetchEndpoints(client: client, eTag: eTag)
		}
	}
	
	/// Fetches the organisations dataset using the provided client and optional ETag.
	/// - Parameters:
	///   - client: The configured OpenAPI client to use for the request.
	///   - eTag: The ETag for conditional request; pass `nil` to always fetch.
	/// - Returns: Tuple of status code, updated ETag and raw data (`nil` on 304).
	private func fetchOrganizations(
		client: Client,
		eTag: String?
	) async throws -> (statusCode: Int, eTag: String?, data: Data?) {
		
		let response = try await client.getOrganizations(
			headers: Operations
				.getOrganizations.Input.Headers(
					If_hyphen_None_hyphen_Match: eTag
				)
		)
		
		switch response {
			case .ok(let output):
				let data = try JSONEncoder().encode(output.body.json)
				return (200, output.headers.ETag, data)
			case .notModified:
				return (304, eTag, nil)
			case let .undocumented(statusCode: code, undocumentedPayload):
				logError("LocalizationAPIClient - Status code: \(code) with payload \(undocumentedPayload)")
				throw LocalizationAPIClientError.undocumented(code)
		}
	}
	
	/// Fetches the endpoints dataset using the provided client and optional ETag.
	/// - Parameters:
	///   - client: The configured OpenAPI client to use for the request.
	///   - eTag: The ETag for conditional request; pass `nil` to always fetch.
	/// - Returns: Tuple of status code, updated ETag and raw data (`nil` on 304).
	private func fetchEndpoints(
		client: Client,
		eTag: String?
	) async throws -> (statusCode: Int, eTag: String?, data: Data?) {
		
		let response = try await client.getEndpoints(
			headers: Operations.getEndpoints
				.Input.Headers(
					If_hyphen_None_hyphen_Match: eTag
				)
		)
		
		switch response {
			case .ok(let output):
				let data = try JSONEncoder().encode(output.body.json)
				return (200, output.headers.ETag, data)
			case .notModified:
				return (304, eTag, nil)
			case let .undocumented(statusCode: code, undocumentedPayload):
				logError("LocalizationAPIClient - Status code: \(code) with payload \(undocumentedPayload)")
				throw LocalizationAPIClientError.undocumented(code)
		}
	}
}
