# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  # -- TESTING -- 

  desc "Run tests for integration purposes"
  lane :test_ci do
    run_tests(
      app_name: "MGO",
      destination: "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2",
      project: "MGO.xcodeproj",
      scheme: "MGO Dev",
      reinstall_app: true,
      app_identifier: "nl.rool.pifz.dev",
      code_coverage: true,
      result_bundle_path: "MGO.xcresult",
      skip_slack: true,
      xcargs: "-skipPackagePluginValidation"
    )
  end
  
  # -- E2E TESTING --

  desc "Run end to end tests"
  lane :e2e_ci do
    run_tests(
      app_name: "MGO",
      destination: "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2",
      project: "MGO.xcodeproj",
      scheme: "MGO UI Tests",
      reinstall_app: true,
      fail_build: true,
      reset_simulator: true,
      number_of_retries: 1,
      app_identifier: "nl.rool.pifz.dev",
      result_bundle_path: "MGO.xcresult",
      skip_slack: true,
      result_bundle: true,
      xcargs: "-skipPackagePluginValidation"
    )
  end

  # -- TestFlight --

  desc "Build and ship the app to TestFlight"
  lane :ship_app_to_testflight do
    ship_to_testflight(
      provisioning_profile_path: "fastlane/profiles/nlrijksoverheidnl_AppStore.mobileprovision",
      xcodeproj: "MGO.xcodeproj",
      targetname: "MGO",
      schemename:  "MGO AppStore",
      configuration: "AppStore",
      provisioningprofilename: "nl.rijksoverheid.pifz: AppStore",
      bundleid: "nl.rijksoverheid.pifz"
    )
  end

  desc "Builds and uploads to Testflight from CI"
  private_lane :ship_to_testflight do |options|

    ENV["TESTFLIGHT_DEPLOY"] = "true"

    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_API_KEY_ID'],
      issuer_id: ENV["APP_STORE_API_KEY_ISSUER"],
      key_filepath: "appstore-apikey.p8",
      duration: 1200,
    )
    
     # unwrap options:
     provisioning_profile_path =   options[:provisioning_profile_path]
     xcodeproj =                   options[:xcodeproj]
     targetname =                  options[:targetname]
     schemename =                  options[:schemename]
     configuration =               options[:configuration]
     provisioningprofilename =     options[:provisioningprofilename]
     bundleid =                    options[:bundleid]                 
 
     # Prepare:
     setup_ci(provider: "travis", force: true)
     prepare_certificate
     install_provisioning_profile(path: provisioning_profile_path)
     
     # Version/Build number
     version = get_version_number(xcodeproj: xcodeproj, target: targetname, configuration: configuration)
     build_number = determine_build_number()
     increment_build_number(build_number: build_number, xcodeproj: xcodeproj)
     
     # Build:
     build_ios_app(
       scheme: schemename,
       configuration: configuration,
       export_options: {
         provisioningProfiles: {
           bundleid => provisioningprofilename
         }
       },
       xcargs: "-skipPackagePluginValidation"
     )

     upload_to_testflight(skip_submission: true)

     inform_slack(
      default_payloads: [:git_author],
      message: "[TESTFLIGHT] :apple: Successfully distributed iOS #{schemename} app build #{version} (#{build_number}) to TestFlight :rocket:",
    )

  end

  # -- DEPLOYING --

  desc "Build and deploy the app for Test via Firebase from CI"
  lane :deploy_test_ci do
    deploy(
      provisioning_profile_path: "fastlane/profiles/MGO_Test.mobileprovision",
      xcodeproj: "MGO.xcodeproj",
      targetname: "MGO",
      schemename:  "MGO Test",
      configuration: "FirebaseTest",
      provisioningprofilename: "MGO Test",
      bundleid: "nl.rool.pifz.test",
      firebaseappid: "1:844514292239:ios:6976aeb782c2d11b3e297a",
      firebasegroupscsv: "test-omgeving"
    )
  end

  desc "Build and deploy the app for Acc via Firebase from CI"
  lane :deploy_acc_ci do
    deploy(
      provisioning_profile_path: "fastlane/profiles/MGO_Acc.mobileprovision",
      xcodeproj: "MGO.xcodeproj",
      targetname: "MGO",
      schemename:  "MGO Acceptance",
      configuration: "FirebaseAcceptance",
      provisioningprofilename: "MGO Acc",
      bundleid: "nl.rool.pifz.acc",
      firebaseappid: "1:844514292239:ios:83659728c65234ce3e297a",
      firebasegroupscsv: "acceptatie-omgeving"
    )
  end
  
  desc "Build and deploy the app for Demo via Firebase from CI"
  lane :deploy_demo_ci do
    deploy(
      provisioning_profile_path: "fastlane/profiles/MGO_Demo.mobileprovision",
      xcodeproj: "MGO.xcodeproj",
      targetname: "MGO",
      schemename:  "MGO Demo",
      configuration: "FirebaseDemo",
      provisioningprofilename: "MGO Demo",
      bundleid: "nl.rool.pifz.demo",
      firebaseappid: "1:844514292239:ios:52e3ba5f9848e0803e297a",
      firebasegroupscsv: "demo-omgeving"
    )
  end
  
  desc "Build and deploy the app for Prod via Firebase from CI"
  lane :deploy_prod_ci do
    deploy(
      provisioning_profile_path: "fastlane/profiles/MGO_Prod.mobileprovision",
      xcodeproj: "MGO.xcodeproj",
      targetname: "MGO",
      schemename:  "MGO Production",
      configuration: "FirebaseProduction",
      provisioningprofilename: "MGO Prod",
      bundleid: "nl.rool.pifz",
      firebaseappid: "1:844514292239:ios:2bbdfebca3a39a673e297a",
      firebasegroupscsv: "productie-omgeving"
    )
  end

  # -- PRIVATE LANES --

  private_lane :deploy do |options|

    # unwrap options:
    provisioning_profile_path =   options[:provisioning_profile_path]
    xcodeproj =                   options[:xcodeproj]
    targetname =                  options[:targetname]
    schemename =                  options[:schemename]
    configuration =               options[:configuration]
    provisioningprofilename =     options[:provisioningprofilename]
    bundleid =                    options[:bundleid]
    firebase_app_id =             options[:firebaseappid]
    firebase_groups_csv =         options[:firebasegroupscsv]

    # Prepare:
    setup_ci(provider: "travis", force: true)
    prepare_certificate
    install_provisioning_profile(path: provisioning_profile_path)
    
    # Version/Build number
    version = get_version_number(xcodeproj: xcodeproj, target: targetname, configuration: configuration)
    build_number = determine_build_number()
    increment_build_number(build_number: build_number, xcodeproj: xcodeproj)
    
    shield(
      version: version,
      build: build_number,
      color: "blue"
    )

    # Build:
    build_ios_app(
      scheme: schemename,
      configuration: configuration,
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: {
          bundleid => provisioningprofilename
        }
      },
      xcargs: "-skipPackagePluginValidation"
    )

    # It's useful to see the originating git branch in Firebase release notes:
    gitbranch = ENV['GITBRANCH'].delete_prefix("refs/heads/")

    # Also useful to see the latest commit message, because often building from `main` anyway:
    gitcommitmessage = `git log -1 --pretty=format:%B`

    if gitbranch == "main"
      releasenotes = "Latest commit: #{gitcommitmessage}"
    else
      releasenotes = "Branch '#{gitbranch}'\nLatest commit: '#{gitcommitmessage}'"
    end

    # Deploy to Firebase:
    firebase_app_distribution(
      app: firebase_app_id,
      groups: firebase_groups_csv,
      release_notes: releasenotes
    )
    
    inform_slack(
      default_payloads: [:git_author],
      message: "Successfully distributed iOS #{schemename} app beta build #{version} (#{build_number}) :rocket:",
    )
  end

  private_lane :prepare_certificate do
    import_certificate(
      certificate_path: ENV["CERTIFICATE_PATH"],
      certificate_password: ENV["CERTIFICATE_PASSWORD"],
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ""
    )
 end

  private_lane :determine_build_number do |options|
    number_of_commits(all: true)
  end

  private_lane :inform_slack do |options|
    unless ENV['SLACK_URL'].nil?
      slack(options)
    end
  end

  private_lane :shield do |options|
    add_badge(shield: "#{options[:version]}-#{options[:build]}-#{options[:color]}", no_badge: true)
  end
end

# We were seeing an issue where fastlane would leave a temporary keychain as the _default_
# macOS keychain, which caused all kinds of issues.
# This lane (running on `after_all` and `error`) will cleanup.
lane :remove_temp_keychain do
  begin
    name = "fastlane_tmp_keychain"
    delete_keychain(
      name: name
    ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
  rescue => ex
    puts(ex)
  end
end

after_all do |lane, options|
  remove_temp_keychain
end

error do |lane, exception, options|

  inform_slack(
    default_payloads: [:git_author],
    message: ":hot_face: FAIL to distribute iOS build for lane #{lane}, error: #{exception}",
    success: false
  )

  remove_temp_keychain
end
