/*
 *  SPDX-FileCopyrightText: 2025 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
 *  SPDX-License-Identifier: EUPL-1.2
 */

import AuthorizationMiddleware
import OpenAPIRuntime
import OpenAPIURLSession
import Foundation
import Logging

public protocol PatientFriendlyTermsAPIClientProtocol {
	
	/// Create a Patient Friendly Terms API Client
	/// - Parameter url: the url to the server
	/// - Parameter username: authentication user name
	/// - Parameter password: authentication password
	init(_ url: Foundation.URL, username: String, password: String)
	
	/// Create a Patient Friendly Terms API Client
	/// - Parameter url: the url to the server
	init(_ url: Foundation.URL)
	
	/// Fetch the terms from the remote server
	/// - Parameter eTag: The ETag for the terms
	/// - Returns: tuple of status code, eTag and terms
	func fetchTerms(eTag: String?) async throws ->
	(statusCode: Int, eTag: String?, terms: PatientFriendlyTerms?)
}

public enum PatientFriendlyTermsAPIClientError: Error, Equatable, Sendable {

	case undocumented(Int)
}

/// The API Client for Patient Friendly Terms
public class PatientFriendlyTermsAPIClient: PatientFriendlyTermsAPIClientProtocol {
	
	/// The url of the server with the terms
	private var serverURL: URL
	
	/// optional authorization middleware for basic auth
	private var authorizationMiddleware: AuthorizationMiddleware?
	
	/// Create a Patient Friendly API Client
	/// - Parameter url: the url to the server
	/// - Parameter username: authentication user name
	/// - Parameter password: authentication password
	required public init(_ url: Foundation.URL, username: String, password: String) {
		
		self.serverURL = url
		self.authorizationMiddleware = AuthorizationMiddleware(
			username: username,
			password: password
		)
	}
	
	/// Create a Patient Friendly API Client
	/// - Parameter url: the url to the server
	required public init(_ url: Foundation.URL) {
		
		self.serverURL = url
	}
	
	/// Autogenerated api client with OpenAPI-generator
	/// - Returns: Open API Client
	func setUpClient() -> Client {
		
		var middlewares = [any ClientMiddleware]()
		if let authorizationMiddleware {
			middlewares.append(authorizationMiddleware)
		}
		middlewares.append(StripHeaderEncodingMiddleware())
		return Client(
			serverURL: serverURL,
			transport: URLSessionTransport(),
			middlewares: middlewares
		)
	}
	
	/// Fetch the terms from the remote server
	/// - Parameter eTag: The ETag for the terms
	/// - Returns: tuple of status code, eTag and terms
	public func fetchTerms(eTag: String?) async throws -> (statusCode: Int, eTag: String?, terms: PatientFriendlyTerms?) {
		
		let client = setUpClient()
		let response = try await client.getPft(
			headers: Operations.getPft.Input.Headers(
				If_hyphen_None_hyphen_Match: eTag
			)
		)
		switch response {
			case .ok(let output):
				// Success, store the terms as json and persist the ETag header
				let terms = try output.body.json
				return (200, output.headers.ETag, terms)
			
			case .notModified:
				// The terms are not modified. Use the downloaded terms
				return (304, eTag, nil)
			
			case let .undocumented(statusCode: statusCode, undocumentedPayload):
				// Not sure what happened.
				logError("PatientFriendlyTermsAPIClient - Status code: \(statusCode) with payload \(undocumentedPayload)")
				throw PatientFriendlyTermsAPIClientError.undocumented(statusCode)
		}
	}
}

public typealias PatientFriendlyTermsServers = Servers
public typealias PatientFriendlyTerms = Operations.getPft.Output.Ok.Body.jsonPayload
public typealias PatientFriendlyTerm = Components.Schemas.PatientFriendlyTerm
