/*
 *  SPDX-FileCopyrightText: 2025 De Staat der Nederlanden, Ministerie van Volksgezondheid, Welzijn en Sport.
 *  SPDX-License-Identifier: EUPL-1.2
 */

import AuthorizationMiddleware
import OpenAPIRuntime
import OpenAPIURLSession
import Foundation

public protocol PatientFriendlyTermsAPIClientProtocol {
	
	/// Create a Patient Friendly Terms API Client
	/// - Parameter url: the url to the server
	/// - Parameter username: authentication user name
	/// - Parameter password: authentication password
	init(_ url: Foundation.URL, username: String, password: String)
	
	/// Create a Patient Friendly Terms API Client
	/// - Parameter url: the url to the server
	init(_ url: Foundation.URL)
	
	/// Fetch the terms from the remote server
	/// - Parameter eTag: The ETag for the terms
	/// - Returns: tuple of status code, eTag and terms
	func fetchTerms(eTag: String?) async throws ->
	(StatusCode: Int, eTag: String?, terms: PatientFriendlyTerms?)
}

public enum PatientFriendlyTermsAPIClientError: Error {

	case undocumented(Int)
}

public class PatientFriendlyTermsAPIClient: PatientFriendlyTermsAPIClientProtocol {
	
	/// Autogenerated api client with OpenAPI-generator
	private var client: Client
	
	/// Create a Patient Friendly API Client
	/// - Parameter url: the url to the server
	/// - Parameter username: authentication user name
	/// - Parameter password: authentication password
	required public init(_ url: Foundation.URL, username: String, password: String) {
		
		self.client = Client(
			serverURL: url,
			transport: URLSessionTransport(),
			middlewares: [
				AuthorizationMiddleware(
					username: username,
					password: password
				)
			]
		)
	}
	
	/// Create a Patient Friendly API Client
	/// - Parameter url: the url to the server
	required public init(_ url: Foundation.URL) {
		
		self.client = Client(
			serverURL: url,
			transport: URLSessionTransport()
		)
	}
	
	/// Fetch the terms from the remote server
	/// - Parameter eTag: The ETag for the terms
	/// - Returns: tuple of status code, eTag and terms
	public func fetchTerms(eTag: String?) async throws -> (StatusCode: Int, eTag: String?, terms: PatientFriendlyTerms?) {
		
		var headers = Operations.get_sol_pft_period_json.Input.Headers()
		
//		let headers = Operations.get_sol_pft_period_json.Input.Headers(If_hyphen_None_hyphen_Match: eTag)
		let response = try await client.get_sol_pft_period_json(headers: headers)
		
		switch response {
			case .ok(let output):
				// Success, store the terms as json and persist the ETag header
				let terms = try output.body.json
				return (200, output.headers.ETag, terms)
			
			case .notModified:
				// The terms are not modified. Use the downloaded terms
				return (304, eTag, nil)
			
			case let .undocumented(statusCode: statusCode, undocumentedPayload):
				// Not sure what happened.
				print("Status code: \(statusCode)")
				print(undocumentedPayload)
				throw PatientFriendlyTermsAPIClientError.undocumented(statusCode)
		}
	}
}

public typealias PatientFriendlyTermsServers = Servers
public typealias PatientFriendlyTerms = Operations.get_sol_pft_period_json.Output.Ok.Body.jsonPayload
 public typealias PatientFriendlyTerm = Components.Schemas.PatientFriendlyTerm
