openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
  - url: https://lo-ad.test.mgo.irealisatie.nl/
    description: MGO TEST localisation
paths:
  "/localization/organization/search":
    post:
      tags:
      - localization
      summary: Search for organizations based on the search parameters
      description: Returns a list of organizations based on the search parameters
      operationId: read_item_localization_organization_search_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
components:
  schemas:
    Address:
      properties:
        active:
          type: boolean
          title: Active
        address:
          type: string
          title: Address
        city:
          type: string
          title: City
        country:
          type: [string, null]
          title: Country
        lines:
          items:
            type: [string, null]
          type: array
          title: Lines
        geolocation:
          schema:
            $ref: "$#/components/schemas/GeoLocation"
          title: GeoLocation
        postalcode:
          type: [string, null]
          title: Postalcode
        state:
          type: [string, null]
          title: State
        type:
          type: string
          title: Type
      type: object
      required:
      - active
      - address
      - city
      - country
      - type
      title: Address
    CType:
      properties:
        code:
          type: string
          title: Code
        display_name:
          type: string
          title: Display Name
        type:
          type: string
          title: Type
      type: object
      required:
      - code
      - display_name
      - type
      title: CType
    GeoLocation:
      properties:
        latitude:
          type: number
          title: Latitude
        longitude:
          type: number
          title: Longitude
      type: object
      required:
      - latitude
      - longitude
      title: GeoLocation
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    IdentificationType:
      type: string
      enum:
      - agb-z
      - medmij
      - htn
      - ura
      title: IdentificationType
    Name:
      properties:
        full_name:
          type: string
          title: Full Name
        preferred:
          type: boolean
          title: Preferred
      type: object
      required:
      - full_name
      - preferred
      title: Name
    Organization:
      properties:
        display_name:
          type: string
          title: Display Name
        identification_type:
          type: string
          title: Identification Type
        identification_value:
          type: string
          title: Identification Value
        active:
          type: boolean
          title: Active
        addresses:
          items:
            $ref: "#/components/schemas/Address"
          type: array
          title: Addresses
        names:
          items:
            $ref: "#/components/schemas/Name"
          type: array
          title: Names
        types:
          items:
            $ref: "#/components/schemas/CType"
          type: array
          title: Types
        data_services:
          items:
            "$ref": "#/components/schemas/ZalDataServiceResponse"
          type: array
          title: Data Services
      type: object
      required:
      - display_name
      - identification_type
      - identification_value
      - active
      - addresses
      - names
      - types
      - data_services
      title: Organization
    SearchRequest:
      properties:
        name:
          type: [string, null]
          title: Name
        city:
          type: [string, null]
          title: City
      type: object
      title: SearchRequest
    SearchResponse:
      properties:
        organizations:
          items:
            $ref: "#/components/schemas/Organization"
          type: array
          title: Organizations
      type: object
      required:
      - organizations
      title: SearchResponse
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ZalDataServiceResponse:
      properties:
        id:
          type: integer
          title: Id
        name:
          type: string
          title: Name
        interface_version:
          type: integer
          title: Interface Version
        auth_endpoint:
          type: string
          title: Auth Endpoint
        token_endpoint:
          type: string
          title: Token Endpoint
        roles:
          items:
            $ref: "#/components/schemas/ZalDataServiceRoleResponse"
          type: array
          title: Roles
      type: object
      required:
      - id
      - name
      - interface_version
      - auth_endpoint
      - token_endpoint
      - roles
      title: ZalDataServiceResponse
    ZalDataServiceRoleResponse:
      properties:
        code:
          type: string
          title: Code
        resource_endpoint:
          type: string
          title: Resource Endpoint
      type: object
      required:
      - code
      - resource_endpoint
      title: ZalDataServiceRoleResponse
