direction: down

# Apple
UIKit: {
  shape: oval
  style.fill: "#8FCAE7"
}
SwiftUI: {
  shape: oval
  style.fill: "#8FCAE7"
}
Foundation: {
  shape: oval
  style.fill: "#8FCAE7"
}
CoreGraphics: {
  shape: oval
  style.fill: "#8FCAE7"
}
CoreText: {
  shape: oval
  style.fill: "#8FCAE7"
}

# Third-Party
NavigationStackBackport: {
  shape: hexagon
}
Logging: {
  shape: hexagon
}

# The application

MGOapp: {
  shape: package
}

MGOapp <- MGOFoundation
MGOapp <- MGOUI
MGOapp <- UIKit

# - Packages -

MGOFoundation { style.fill: "#ffcc00" }
MGOFoundation <- Logging
MGOFoundation <- Foundation
MGOFoundation <- Managers

MGOUI { style.fill: "#ffcc00" }
MGOUI <- SwiftUI
MGOUI <- NavigationStackBackport
MGOUI <- ReusableUI
MGOUI <- RijksoverheidFont

Managers { style.fill: "#ffcc00" }

RijksoverheidFont { style.fill: "#ffcc00" }
RijksoverheidFont <- SwiftUI
RijksoverheidFont <- CoreGraphics
RijksoverheidFont <- CoreText

ReusableUI { style.fill: "#ffcc00" }
ReusableUI <- SwiftUI
