direction: down

# Apple
UIKit: {
  shape: oval
  style.fill: "#8FCAE7"
}
SwiftUI: {
  shape: oval
  style.fill: "#8FCAE7"
}
Webkit: {
  shape: oval
  style.fill: "#8FCAE7"
}
Foundation: {
  shape: oval
  style.fill: "#8FCAE7"
}
CommonCrypto: {
  shape: oval
  style.fill: "#8FCAE7"
}
CryptoKit: {
  shape: oval
  style.fill: "#8FCAE7"
}
CoreGraphics: {
  shape: oval
  style.fill: "#8FCAE7"
}
CoreText: {
  shape: oval
  style.fill: "#8FCAE7"
}
JavaScriptCore: {
  shape: oval
  style.fill: "#8FCAE7"
}
PDFKit: {
  shape: oval
  style.fill: "#8FCAE7"
}
swift-openapi-generator: {
  shape: oval
  style.fill: "#8FCAE7"
}
swift-openapi-runtime: {
  shape: oval
  style.fill: "#8FCAE7"
}
swift-openapi-urlsession: {
  shape: oval
  style.fill: "#8FCAE7"
}
swift-http-types: {
  shape: oval
  style.fill: "#8FCAE7"
}
QuickLook {
  shape: oval
  style.fill: "#8FCAE7"
}

# Third-Party
FactoryKit: {
  shape: hexagon
}
Foil: {
  shape: hexagon
}
GRDB: {
  shape: hexagon
}
NavigationStackBackport: {
  shape: hexagon
}
iOSSecuritySuite: {
  shape: hexagon
}
SwiftLogging: {
  shape: hexagon
}
DeviceKit: {
  shape: hexagon
}
OHHTTPStubs: {
  shape: hexagon
}
SwiftSoup: {
  shape: hexagon
}
SwiftUIIntrospect: {
  shape: hexagon
}

# The application

MGOapp: {
  shape: package
}

MGOapp <- MGODebug
MGOapp <- MGOFoundation
MGOapp <- MGOUI
MGOapp <- PdfExport
MGOapp <- QuickLook
MGOapp <- RestrictedBrowser
MGOapp <- UIKit

# - Packages -

FeatureFlag { style.fill: "#ffcc00" }

FHIRClient { style.fill: "#ffcc00" }

FileStorage { style.fill: "#ffcc00" }
FileStorage <- MGODebug
FileStorage <- Observatory

HCIMCore { style.fill: "#ffcc00" }
HCIMCore <- JavaScriptCore
HCIMCore <- MGODebug

JailBreakDetector { style.fill: "#ffcc00" }
JailBreakDetector <- iOSSecuritySuite

Localization { style.fill: "#ffcc00" }
Localization <- OpenAPICore
Localization <- OpenAPIMiddleware
Localization <- FileStorage
Localization <- MGODebug
Localization <- swift-openapi-generator

MGODebug { style.fill: "#ffcc00" }
MGODebug <- SwiftLogging

MGOFoundation { style.fill: "#ffcc00" }
MGOFoundation <- FactoryKit
MGOFoundation <- FeatureFlag
MGOFoundation <- Foundation
MGOFoundation <- JailBreakDetector
MGOFoundation <- MGODebug
MGOFoundation <- MGORepository
MGOFoundation <- NotificationCenter
MGOFoundation <- Observatory
MGOFoundation <- OrganizationSearch
MGOFoundation <- OHHTTPStubs
MGOFoundation <- NetworkAvailability
MGOFoundation <- PatientFriendlyTerms
MGOFoundation <- Sanitizer
MGOFoundation <- SecureUserSettings
MGOFoundation <- RemoteAuthentication
MGOFoundation <- RemoteConfiguration

MGORepository  { style.fill: "#ffcc00" }
MGORepository <- FHIRClient
MGORepository <- Observatory
MGORepository <- HCIMCore

MGOUI { style.fill: "#ffcc00" }
MGOUI <- DeviceKit
MGOUI <- NavigationStackBackport
MGOUI <- OSVersion
MGOUI <- ReusableUI
MGOUI <- SwiftUI

NetworkAvailability { style.fill: "#ffcc00" }

NotificationCenter { style.fill: "#ffcc00" }
NotificationCenter <- UIKit

Observatory { style.fill: "#ffcc00" }

OpenAPICore { style.fill: "#ffcc00" }
OpenAPICore <- swift-openapi-runtime
OpenAPICore <- swift-openapi-urlsession

OpenAPIMiddleware { style.fill: "#ffcc00" }
OpenAPIMiddleware <- OpenAPICore
OpenAPIMiddleware <- swift-http-types

OrganizationSearch { style.fill: "#ffcc00" }
OrganizationSearch <- CryptoKit
OrganizationSearch <- GRDB
OrganizationSearch <- MGODebug
OrganizationSearch <- Observatory

OSVersion { style.fill: "#ffcc00" }

PatientFriendlyTerms { style.fill: "#ffcc00" }
PatientFriendlyTerms <- OpenAPICore
PatientFriendlyTerms <- OpenAPIMiddleware
PatientFriendlyTerms <- FileStorage
PatientFriendlyTerms <- Foil
PatientFriendlyTerms <- MGODebug
PatientFriendlyTerms <- swift-openapi-generator

PdfExport { style.fill: "#ffcc00" }
PdfExport <- PDFKit

RemoteAuthentication { style.fill: "#ffcc00" }
RemoteAuthentication <- OpenAPICore
RemoteAuthentication <- OpenAPIMiddleware
RemoteAuthentication <- MGODebug
RemoteAuthentication <- swift-openapi-generator

RemoteConfiguration { style.fill: "#ffcc00" }
RemoteConfiguration <- OpenAPICore
RemoteConfiguration <- FileStorage
RemoteConfiguration <- MGODebug
RemoteConfiguration <- Observatory
RemoteConfiguration <- swift-openapi-generator

RestrictedBrowser { style.fill: "#ffcc00" }
RestrictedBrowser <- SwiftUI
RestrictedBrowser <- Theme
RestrictedBrowser <- WebKit
RestrictedBrowser <- ReusableUI

ReusableUI { style.fill: "#ffcc00" }
ReusableUI <- RijksoverheidFont
ReusableUI <- SwiftUI
ReusableUI <- SwiftUIIntrospect
ReusableUI <- Theme

RijksoverheidFont { style.fill: "#ffcc00" }
RijksoverheidFont <- CoreGraphics
RijksoverheidFont <- CoreText
RijksoverheidFont <- DeviceKit
RijksoverheidFont <- SwiftUI

Sanitizer { style.fill: "#ffcc00" }
Sanitizer <- SwiftSoup

SecureUserSettings { style.fill: "#ffcc00" }
SecureUserSettings <- CommonCrypto

Theme { style.fill: "#ffcc00" }
Theme <- SwiftUI
