direction: down

# Apple
example-package-figlet: {
  shape: oval
  style.fill: "#8FCAE7"
}
swift-argument-parser: {
  shape: oval
  style.fill: "#8FCAE7"
}
swift-openapi-runtime: {
  shape: oval
  style.fill: "#8FCAE7"
}
swift-http-types: {
  shape: oval
  style.fill: "#8FCAE7"
}

# Third-Party

github-rest-api-swift-openapi: {
  shape: hexagon
}

# The scripts

CopyImport: {
  shape: document
}
GitHubArtifactDownload: {
  shape: document
}

CopyImport <- MGOCommandLine

GitHubArtifactDownload <- AuthorizationMiddleware
GitHubArtifactDownload <- github-rest-api-swift-openapi
GitHubArtifactDownload <- MGOCommandLine

# - Packages -

AuthorizationMiddleware { style.fill: "#ffcc00" }
AuthorizationMiddleware <- swift-openapi-runtime
AuthorizationMiddleware <- swift-http-types

MGOCommandLine { style.fill: "#ffcc00" }
MGOCommandLine <- example-package-figlet
MGOCommandLine <- swift-argument-parser
