# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Deploy: TestFlight"

on:
  push:
    tags:
      - 'Release-*.*.*-RC*'
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_16.3.0.app/Contents/Developer
  APPSTORE_KEY_BASE64_FILENAME: appstore-apikey.p8
  FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 180
  FASTLANE_XCODEBUILD_SETTINGS_RETRIES: 10

jobs:
  upload:
    if: github.event.repository.name == 'nl-mgo-app-ios-private'
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Log Build Number
        run: |
          ./Scripts/log-build-number.sh

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Homebrew
        run: |
          make homebrew_ci

      - name: Build mint dependencies
        uses: ./.github/actions/build-mint

      - name: Checkout LFS resources
        run: |
          git lfs pull
          git checkout .

      - name: Generate project
        env:
          MGO_BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USER }}
          MGO_BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
        run: |
          make generate_project

      - name: Write p8 Key
        if: github.event.repository.name == 'nl-mgo-app-ios-private'
        env:
          APP_STORE_API_KEY_P8_BASE64: ${{ secrets.APP_STORE_API_KEY_P8 }}
        run: |
          echo $APP_STORE_API_KEY_P8_BASE64 | base64 --decode > $APPSTORE_KEY_BASE64_FILENAME # not certain this is p8 format
          
      - name: Load certificate
        env:
          CERTIFICATE_CONTENTS: ${{ secrets.DIST_CERT_CONTENTS }}
        run: |
          mkdir fastlane/certificates
          echo "$CERTIFICATE_CONTENTS" | base64 --decode > fastlane/certificates/distribution.p12

      - name: Ship MGO to TestFlight
        timeout-minutes: 120
        env:
          CERTIFICATE_PATH: fastlane/certificates/distribution.p12
          CERTIFICATE_PASSWORD: ${{ secrets.DIST_CERT_PASSWORD }}
          SLACK_URL: ${{ secrets.SLACK_URL }}
          APP_STORE_API_KEY_ID: ${{ secrets.APP_STORE_API_KEY_ID }}
          APP_STORE_API_KEY_ISSUER: ${{ secrets.APP_STORE_API_KEY_ISSUER }}
        run: |
          bundle exec fastlane ios ship_app_to_testflight

      - name: Archive MGO
        uses: actions/upload-artifact@v4
        with:
          name: MGO App
          path: MGO.ipa
          retention-days: 30

      - name: Archive MGO dSYMs
        uses: actions/upload-artifact@v4
        with:
          name: MGO App dSYMs
          path: MGO.app.dSYM.zip
          retention-days: 30
